### ISSUE TITLE
Cryptography has ssl st

### ISSUE THREAD

**Issue by Hellenab** [runfalk/certbot-loopia#3]
Getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/local/lib/python3.5/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 115, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'
```
Not sure if I'm doing something wrong or if there's actually something missing.

**Comment by runfalk** [comment]
That doesn't seem to originate in this library. This is most likely a problem on your side. Try installing it in a virtualenv and see if that fixes it. There might be some kind of version mismatch due to previously installed dependencies.

**Comment by Hellenab** [comment]
You were right, it was a problem with certbot, not with the library. Thanks! :)
